name: web
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.12=h4c7d964_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.12.12=py312hd8ed1ab_1
  - debugpy=1.8.17=py312ha1a9051_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h9214b88_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.8.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - krb5=1.21.3=hdf4eb48_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=hc70643c_0
  - libzlib=1.3.1=h02ab6af_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py312he5662c2_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.12.12=h716150d_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.12.12=hd8ed1ab_1
  - python_abi=3.12=3_cp312
  - pywin32=311=py312h829343e_1
  - pyzmq=27.1.0=py312hbb5da91_0
  - setuptools=80.9.0=py312haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hf199647_0
  - tornado=6.5.2=py312he06e257_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - annotated-types==0.7.0
      - anyio==4.12.0
      - blinker==1.9.0
      - bokeh==3.8.1
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - distro==1.9.0
      - dotenv==0.9.9
      - flask==3.1.2
      - fonttools==4.60.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - llvmlite==0.45.1
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mordredcommunity==2.0.6
      - narwhals==2.12.0
      - networkx==3.6
      - numba==0.62.1
      - numpy==2.3.5
      - openai==2.8.1
      - pandas==2.3.3
      - pillow==12.0.0
      - plotly==6.5.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - rdkit==2025.9.1
      - requests==2.32.5
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - sniffio==1.3.1
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - xyzservices==2025.11.0
prefix: C:\Users\33433\miniconda3\envs\web
